=== hi-noikiy/hiren452/app/code/Plumrocket/AmpEmail/etc/pramp_email_templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_AmpEmail
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="emailTemplateType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="file" type="xs:string" use="required"/>
        <xs:attribute name="module" type="xs:string" use="required"/>
        <xs:attribute name="area" type="areaType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="areaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="frontend"/>
            <xs:enumeration value="adminhtml"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="template" type="emailTemplateType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hi-noikiy/hiren452/app/code/Plumrocket/AmpEmail/etc/pramp_email_templates.xml
<?xml version="1.0"?>
<!--
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_AmpEmail
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Plumrocket_AmpEmail:etc/pramp_email_templates.xsd">
    <template id="design_email_header_template" label="Email Header" file="header.html" module="Plumrocket_AmpEmail" area="frontend"/>
    <template id="design_email_footer_template" label="Email Footer" file="footer.html" module="Plumrocket_AmpEmail" area="frontend"/>

    <template id="newsletter_subscription_confirm_email_template"
              label="Subscription Confirmation"
              file="newsletter/subscr_confirm.html"
              module="Plumrocket_AmpEmail"
              area="frontend"
    />

    <template id="customer_create_account_email_template"
              label="New Account"
              file="customer/new_account.html"
              module="Plumrocket_AmpEmail"
              area="frontend"
    />

    <template id="catalog_productalert_email_stock_template"
              label="Stock Alert"
              file="product_alert/stock_alert.html"
              module="Plumrocket_AmpEmail"
              area="frontend"
    />

    <template id="catalog_productalert_email_price_template"
              label="Price Alert"
              file="product_alert/price_alert.html"
              module="Plumrocket_AmpEmail"
              area="frontend"
    />

    <template id="sales_email_order_template"
              label="New Order"
              file="sales/order_new.html"
              module="Plumrocket_AmpEmail"
              area="frontend"
    />

    <template id="sales_email_order_guest_template"
              label="New Order for Guest"
              file="sales/order_new_guest.html"
              module="Plumrocket_AmpEmail"
              area="frontend"
    />
</config>
